### ISSUE TITLE
Mindight Commander is unreadable with this theme

### ISSUE THREAD

**Issue by phpony** [catppuccin/windows-terminal#2]
This theme does not provide enough contrast for console based gui apps like [mc](https://github.com/MidnightCommander/mc) and many others.

This is how it looks with catppuccin theme:
![mc](https://user-images.githubusercontent.com/480287/157030679-fe01d13b-de73-4038-acdb-3ec04632d448.png)

This is how it looks with look-a-like [dracula theme](https://github.com/dracula/windows-terminal):
![mcdrac](https://user-images.githubusercontent.com/480287/157031100-ada149d9-8d2e-4467-82e0-1b9a628f9698.png)

I'd suggest to darken the bg fill color a bit and lighten the main fg color maybe?

**Comment by nekowinston** [comment]
Could someone confirm that this is still an issue with the 0.2.0 update?

cc: @AdalZanabria

**Comment by AdalZanabria** [comment]
After the 0.2.0, the Catppuccin theme now comes in 4 flavours, one of them (Latte) is made for high contrast:
<img width="960" alt="latte" src="https://user-images.githubusercontent.com/57764806/181126594-9557f966-21cf-4456-9f96-1e9ed0d5fbee.png">

The thing is that mc uses a weird colorscheme using "blue" as background and "white" as foreground instead of the usual background and foreground colors from the terminal... I will start working on a port for this specific tool, in the mean time, you can alias midnight commander to "mc -b" which starts the program without color:
<img width="960" alt="mc-b" src="https://user-images.githubusercontent.com/57764806/181126900-5eeffe47-864e-4052-a0c9-f02605dec543.png">

**Comment by nekowinston** [comment]
`mc -b` doesn't look to bad, at least it's legible.

This seems like it's not an issue with the port, since it follows the palette spec. Similar issues have been reported when using `gitui`. It's likely that tools like it will require custom ports as well.

![CleanShot 2022-07-27 at 01 09 58](https://user-images.githubusercontent.com/79978224/181127527-d5601eab-1bcf-4629-a3ff-5f43c56d4019.png)

This is the WezTerm port which I maintain, and buttons are hard to read as well, without tweaking the application theme.

> I will start working on a port for this specific tool

Much appreciated!

**Comment by AdalZanabria** [comment]
[Midnight Commander](https://github.com/catppuccin/mc) port for catppuccin is up, this will fix the visual problem regardless of the terminal @phpony 😺
